{"name": "批量登录用户", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'url'", "trace": "name = 'yujl47', pwd = 'Jg82SqEi1', assertion = 9999\n\n    @pytest.mark.parametrize('name,pwd,assertion', cases, ids=ids)\n    @allure.title(\"批量登录用户\")\n    def test_login(name, pwd, assertion):\n        url = 'http://qa.yansl.com:8084/login'\n        req = {\n            \"pwd\": pwd,\n            \"userName\": name\n        }\n>       resp = request_tool.post_json(url, json=req)\n\ntest_case\\User\\test_login.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nargs = ('http://qa.yansl.com:8084/login',)\nkwargs = {'json': {'pwd': 'Jg82SqEi1', 'userName': 'yujl47'}}, r = ()\n\n    def _func(*args, **kwargs):\n        r= func(*args, **kwargs)\n        request = \"-------------------request-------------\" \\\n>                 \"\\n{0}\\n{1}\\n{2}\".format(r.url, string_tool.dic_to_str(r.request.headers), r.request.body)\nE       AttributeError: 'tuple' object has no attribute 'url'\n\ntools\\report\\decorators_tool.py:11: AttributeError"}, "attachments": [{"name": "log", "source": "f27c216d-7a01-4224-9798-43e32074ed0f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "name", "value": "'yujl47'"}, {"name": "pwd", "value": "'Jg82SqEi1'"}, {"name": "assertion", "value": "9999"}], "start": 1602684334471, "stop": 1602684345941, "uuid": "464610fb-900a-4805-b491-6e9d026fe6c2", "historyId": "3f7836a6e80601c7fe231bb15b499df4", "fullName": "test_case.User.test_login#test_login[密码错误]", "labels": [{"name": "parentSuite", "value": "test_case.User"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-679Q8H2"}, {"name": "thread", "value": "9868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.User.test_login"}]}