{"name": "新密码登录成功", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'url'", "trace": "@allure.title(\"新密码登录成功\")\n    def test_changedlogin():\n        url = 'http://qa.yansl.com:8084/login'\n        req = {\n            \"pwd\": \"123456zjc\",\n            \"userName\":\"dru795\"\n        }\n>       resp = request_tool.post_json(url, json=req)\n\ntest_case\\User\\test_oldpwd.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nargs = ('http://qa.yansl.com:8084/login',)\nkwargs = {'json': {'pwd': '123456zjc', 'userName': 'dru795'}}, r = ()\n\n    def _func(*args, **kwargs):\n        r= func(*args, **kwargs)\n        request = \"-------------------request-------------\" \\\n>                 \"\\n{0}\\n{1}\\n{2}\".format(r.url, string_tool.dic_to_str(r.request.headers), r.request.body)\nE       AttributeError: 'tuple' object has no attribute 'url'\n\ntools\\report\\decorators_tool.py:11: AttributeError"}, "attachments": [{"name": "log", "source": "7fd6c621-21d4-458a-a2da-f38c909fc72f-attachment.txt", "type": "text/plain"}], "start": 1602684501191, "stop": 1602684509717, "uuid": "f197ed2e-7bc7-4eb0-8945-b8c7c48decb3", "historyId": "62900d21a3f254a4bc21b0e4d33fef52", "fullName": "test_case.User.test_oldpwd#test_changedlogin", "labels": [{"name": "parentSuite", "value": "test_case.User"}, {"name": "suite", "value": "test_oldpwd"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-679Q8H2"}, {"name": "thread", "value": "11428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.User.test_oldpwd"}]}