{"name": "批量登录用户", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'url'", "trace": "name = '123zjc', pwd = '123456zjc', assertion = 2000\n\n    @pytest.mark.parametrize('name,pwd,assertion', cases, ids=ids)\n    @allure.title(\"批量登录用户\")\n    def test_login(name, pwd, assertion):\n        url = 'http://qa.yansl.com:8084/login'\n        req = {\n            \"pwd\": pwd,\n            \"userName\": name\n        }\n>       resp = request_tool.post_json(url, json=req)\n\ntest_case\\User\\test_login.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nargs = ('http://qa.yansl.com:8084/login',)\nkwargs = {'json': {'pwd': '123456zjc', 'userName': '123zjc'}}, r = ()\n\n    def _func(*args, **kwargs):\n        r= func(*args, **kwargs)\n        request = \"-------------------request-------------\" \\\n>                 \"\\n{0}\\n{1}\\n{2}\".format(r.url, string_tool.dic_to_str(r.request.headers), r.request.body)\nE       AttributeError: 'tuple' object has no attribute 'url'\n\ntools\\report\\decorators_tool.py:11: AttributeError"}, "attachments": [{"name": "log", "source": "8ed321eb-cf30-4f24-bba6-5a7e82a9cb70-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "name", "value": "'123zjc'"}, {"name": "pwd", "value": "'123456zjc'"}, {"name": "assertion", "value": "2000"}], "start": 1602684447410, "stop": 1602684452579, "uuid": "f37afa0f-031d-4c23-ae7b-10e572e9ca76", "historyId": "d41b90ce8422808a1f1148a485dda34b", "fullName": "test_case.User.test_login#test_login[正确数据]", "labels": [{"name": "parentSuite", "value": "test_case.User"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-679Q8H2"}, {"name": "thread", "value": "11428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.User.test_login"}]}